In [4]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

file_path='2016_Annual_Crime_Data.csv'
data=pd.read_csv(file_path, sep=',', header=0, delimiter=',',encoding='iso-8859-1')

In [5]:
data

,GO Primary Key,Council District,GO Highest Offense Desc,Highest NIBRS/UCR Offense Description,GO Report Date,GO Location,Clearance Status,Clearance Date,GO District,GO Location Zip,GO Census Tract,GO X Coordinate,GO Y Coordinate
0,"201,610,188",8.0,AGG ASLT ENHANC STRANGL/SUFFOC,Agg Assault,1-Jan-16,8600 W SH 71 ...,C,12-Jan-16,D,78735.0,19.08,"3,067,322","10,062,796"
1,"201,610,643",9.0,THEFT,Theft,1-Jan-16,219 E 6TH ST ...,C,4-Jan-16,G,78701.0,11,"3,114,957","10,070,462"
2,"201,610,892",4.0,AGG ROBBERY/DEADLY WEAPON,Robbery,1-Jan-16,701 W LONGSPUR BLVD ...,N,3-May-16,E,78753.0,18.23,"3,129,181","10,106,923"
3,"201,610,893",9.0,THEFT,Theft,1-Jan-16,404 COLORADO ST ...,N,22-Jan-16,G,78701.0,11,"3,113,643","10,070,357"
4,"201,611,018",4.0,SEXUAL ASSAULT W/ OBJECT,Rape,1-Jan-16,NaN,C,10-Mar-16,E,78753.0,18.33,NaN,NaN
5,"201,611,148",1.0,DEADLY CONDUCT,Agg Assault,1-Jan-16,8002 TAPO LN ...,N,8-Jan-16,C,78724.0,22.08,"3,146,947","10,077,985"
6,"201,611,198",3.0,ROBBERY BY ASSAULT,Robbery,1-Jan-16,1601 ROYAL CREST DR ...,N,1-Nov-16,H,78741.0,23.16,"3,118,667","10,060,221"
7,"201,611,200",3.0,AGG ASSAULT FAM/DATE VIOLENCE,Agg Assault,1-Jan-16,1600 WICKERSHAM LN ...,C,1-Jan-16,H,78741.0,23.18,"3,122,230","10,059,265"
8,"201,611,224",5.0,AGG ASLT STRANGLE/SUFFOCATE,Agg Assault,1-Jan-16,4009 VICTORY DR ...,C,3-Feb-16,D,78704.0,20.04,"3,099,793","10,058,337"
9,"201,611,233",5.0,BURGLARY NON RESIDENCE,Burglary,1-Jan-16,811 W SLAUGHTER LN ...,N,4-Feb-16,F,78748.0,24.21,"3,095,553","10,035,959"
10,"201,611,261",4.0,BURGLARY OF RESIDENCE,Burglary,1-Jan-16,8930 GALEWOOD DR ...,C,12-Feb-16,E,78758.0,18.2,"3,121,931","10,106,738"
11,"201,611,266",4.0,AUTO THEFT,Auto Theft,1-Jan-16,9619 POINT VISTA PL ...,N,1-Jan-16,E,78753.0,18.33,"3,133,869","10,103,524"
12,"201,611,280",2.0,AUTO THEFT,Auto Theft,1-Jan-16,4323 S IH 35 SVRD NB ...,N,1-Jan-16,F,78744.0,24.11,"3,111,632","10,050,167"
13,"201,611,298",2.0,DEADLY CONDUCT,Agg Assault,1-Jan-16,5804 NEEDLE NOOK CT ...,N,4-Jan-16,F,78744.0,24.31,"3,115,830","10,042,476"
14,"201,611,311",5.0,BURGLARY OF RESIDENCE,Burglary,1-Jan-16,10800 RIVER PLANTATION DR ...,N,5-Jan-16,F,78747.0,24.28,"3,102,916","10,023,485"
15,"201,611,329",5.0,BURGLARY OF RESIDENCE,Burglary,1-Jan-16,9409 BERNOULLI DR ...,N,5-Jan-16,F,78748.0,17.46,"3,085,304","10,039,671"
16,"201,611,337",9.0,AGG ASLT STRANGLE/SUFFOCATE,Agg Assault,1-Jan-16,1100 E OLTORF ST ...,N,6-Jan-16,H,78704.0,23.08,"3,113,907","10,059,041"
17,"201,611,366",7.0,AGG ASSAULT FAM/DATE VIOLENCE,Agg Assault,1-Jan-16,5515 WOODROW AVE ...,N,20-Jan-16,I,78756.0,2.05,"3,116,795","10,092,335"
18,"201,611,374",9.0,RAPE,Rape,1-Jan-16,NaN,N,16-Feb-16,B,78751.0,2.03,NaN,NaN
19,"201,611,390",6.0,BURGLARY OF RESIDENCE,Burglary,1-Jan-16,4400 ANDALUSIA DR ...,C,20-Apr-16,A,78759.0,17.54,"3,114,668","10,121,066"
20,"201,611,422",9.0,BURGLARY OF RESIDENCE,Burglary,1-Jan-16,2338 WILSON ST ...,N,5-Jan-16,D,78704.0,13.05,"3,110,158","10,060,953"
21,"201,611,424",9.0,BURGLARY OF RESIDENCE,Burglary,1-Jan-16,2041 ZACH SCOTT ST ...,N,5-Jan-16,B,78723.0,3.06,"3,126,322","10,080,484"
22,"201,611,441",9.0,BURGLARY NON RESIDENCE,Burglary,1-Jan-16,323 E 6TH ST ...,N,21-Jan-16,G,78701.0,11,"3,115,326","10,070,387"
23,"201,611,449",4.0,SEXUAL ASSAULT W/ OBJECT,Rape,1-Jan-16,NaN,C,2-Jan-16,I,78752.0,15.03,NaN,NaN
24,"201,611,450",5.0,BURGLARY OF RESIDENCE,Burglary,1-Jan-16,1119 ECHO LN ...,N,5-Jan-16,F,78745.0,24.24,"3,097,863","10,045,181"
25,"201,611,494",5.0,BURGLARY NON RESIDENCE,Burglary,1-Jan-16,10140 OLD SAN ANTONIO RD ...,N,5-Feb-16,F,78748.0,24.07,"3,098,369","10,028,961"
26,"201,611,547",3.0,BURGLARY NON RESIDENCE,Burglary,1-Jan-16,903 MONTOPOLIS DR ...,N,1-Mar-16,H,78741.0,23.12,"3,129,173","10,059,178"
27,"201,611,564",8.0,BURGLARY NON RESIDENCE,Burglary,1-Jan-16,5100 ROADRUNNER LN ...,N,5-Feb-16,D,78749.0,17.49,"3,086,212","10,058,406"
28,"201,611,574",9.0,BURGLARY OF VEHICLE,Theft,1-Jan-16,119 E 10TH ST ...,N,14-Jan-16,G,78701.0,11,"3,115,057","10,071,995"
29,"201,611,627",7.0,THEFT BY SHOPLIFTING,Theft,1-Jan-16,3311 ESPERANZA XING ...,N,14-Jan-16,A,78758.0,18.49,"3,118,197","10,118,869"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37431,"20,163,662,189",1.0,AGG ROBBERY/DEADLY WEAPON,Robbery,31-Dec-16,7801 FM 969 RD ...,C,19-Jan-17,C,78725.0,22.08,"3,144,951","10,075,727"
37432,"20,165,053,766",2.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,12820 QUIRIN DR ...,N,2-Jan-17,H,78617.0,24.33,"3,154,685","10,037,363"
37433,"20,165,053,767",1.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,12041 DESSAU RD ...,N,2-Jan-17,E,78754.0,18.34,"3,141,933","10,112,339"
37434,"20,165,053,771",3.0,THEFT,Theft,31-Dec-16,2707 S IH 35 SVRD NB ...,NaN,NaN,H,78741.0,23.07,"3,114,497","10,056,575"
37435,"20,165,053,772",9.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,2701 RIO GRANDE ST ...,N,3-Jan-17,B,78705.0,6.03,"3,113,680","10,079,726"
37436,"20,165,053,778",8.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,6636 W WILLIAM CANNON DR ...,N,11-Jan-17,D,78735.0,19.15,"3,076,772","10,061,056"
37437,"20,165,053,780",5.0,THEFT,Theft,31-Dec-16,4211 S LAMAR BLVD NB ...,N,4-Jan-17,D,78704.0,20.04,"3,098,880","10,058,093"
37438,"20,165,053,781",5.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,5705 WEST GATE BLVD ...,N,4-Jan-17,D,78745.0,17.13,"3,094,374","10,052,233"
37439,"20,165,053,785",7.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,5400 N LAMAR BLVD ...,N,3-Jan-17,I,78756.0,2.05,"3,118,092","10,090,506"
37440,"20,165,053,786",3.0,THEFT OF BICYCLE,Theft,31-Dec-16,2716 E 3RD ST ...,N,22-Feb-17,C,78702.0,9.02,"3,124,129","10,066,233"
37441,"20,165,053,788",3.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,2201 MONTOPOLIS DR ...,N,2-Jan-17,H,78741.0,23.12,"3,126,801","10,054,469"
37442,"20,165,053,789",9.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,3909 N IH 35 SVRD NB ...,N,2-Jan-17,C,78722.0,3.07,"3,122,010","10,081,176"
37443,"20,165,053,792",9.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,1620 E RIVERSIDE DR ...,NaN,NaN,H,78741.0,23.04,"3,118,446","10,062,525"
37444,"20,165,053,793",7.0,THEFT,Theft,31-Dec-16,9061 RESEARCH BLVD NB ...,N,2-Jan-17,A,78758.0,18.49,"3,118,443","10,109,473"
37445,"20,165,053,798",1.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,12041 DESSAU RD ...,N,2-Jan-17,E,78754.0,18.34,"3,141,933","10,112,339"
37446,"20,165,053,813",4.0,THEFT,Theft,31-Dec-16,8601 RESEARCH BLVD SVRD NB ...,N,2-Jan-17,E,78758.0,18.05,"3,121,691","10,105,147"
37447,"20,165,053,814",2.0,THEFT,Theft,31-Dec-16,6607 S IH 35 SVRD NB ...,N,4-Jan-17,F,78744.0,24.27,"3,106,736","10,041,724"
37448,"20,165,053,817",8.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,4970 W US 290 HWY WB ...,N,4-Jan-17,D,78735.0,19.15,"3,090,597","10,057,931"
37449,"20,165,053,821",7.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,2211 W NORTH LOOP BLVD ...,N,4-Jan-17,B,78756.0,2.06,"3,114,330","10,091,389"
37450,"20,165,053,827",8.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,5604 SOUTHWEST PKWY ...,N,11-Jan-17,D,78735.0,19.14,"3,082,154","10,062,686"
37451,"20,165,053,828",8.0,THEFT,Theft,31-Dec-16,5106 MAULDING PASS ...,N,4-Jan-17,D,78749.0,17.49,"3,081,732","10,055,829"
37452,"20,165,053,834",3.0,THEFT,Theft,31-Dec-16,2200 S PLEASANT VALLEY RD ...,N,22-Feb-17,H,78741.0,23.16,"3,119,912","10,057,599"
37453,"20,165,053,836",2.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,901 LITTLE TEXAS LN ...,N,4-Jan-17,F,78745.0,24.02,"3,106,553","10,045,028"
37454,"20,165,053,840",NaN,THEFT,Theft,31-Dec-16,7 BLUE QUAIL DR ...,NaN,NaN,E,NaN,NaN,"3,132,128","10,107,647"
37455,"20,165,053,843",4.0,THEFT,Theft,31-Dec-16,7500 BLESSING AVE ...,N,16-Feb-17,I,78752.0,18.12,"3,129,407","10,094,386"
37456,"20,165,053,846",7.0,THEFT,Theft,31-Dec-16,8822 MC CANN DR ...,N,3-Jan-17,B,78757.0,18.17,"3,117,454","10,109,065"
37457,"20,165,053,849",9.0,THEFT,Theft,31-Dec-16,123 W 6TH ST ...,N,3-Jan-17,G,78701.0,11,"3,113,924","10,070,794"
37458,"20,168,005,740",1.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,5601 EXETER DR ...,N,16-Jan-17,I,78723.0,21.06,"3,132,812","10,084,356"
37459,"20,168,005,742",3.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,101 HERGOTZ LN ...,N,12-Jan-17,H,78742.0,23.1,"3,131,778","10,062,481"
37460,"20,168,005,744",9.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,701 W 28TH ST ...,N,16-Jan-17,B,78705.0,6.03,"3,113,521","10,079,906"

In [6]:
 np.unique(data['Highest NIBRS/UCR Offense Description'])

array(['Agg Assault', 'Auto Theft', 'Burglary', 'Murder', 'Rape',
       'Robbery', 'Theft'], dtype=object)

In [7]:
category=pd.read_csv('category_Austin.csv', sep=',', header=0, delimiter=',')
category.head()

   Unnamed: 0     CATEGORY  crime  score
0           0  Agg Assault      1     70
1           1   Auto Theft      1     50
2           2     Burglary      1     40
3           3       Murder      1    100
4           4         Rape      1     95

In [8]:
crime = data.dropna().drop(['GO Primary Key','Council District','GO Highest Offense Desc','GO Report Date','GO Location','Clearance Status'], axis=1)

In [9]:
crime = crime.dropna().drop(['Clearance Date','Clearance Date','GO District','GO Census Tract','GO X Coordinate','GO Y Coordinate'], axis=1)

In [10]:
crime

      Highest NIBRS/UCR Offense Description  GO Location Zip
0                               Agg Assault          78735.0
1                                     Theft          78701.0
2                                   Robbery          78753.0
3                                     Theft          78701.0
5                               Agg Assault          78724.0
6                                   Robbery          78741.0
7                               Agg Assault          78741.0
8                               Agg Assault          78704.0
9                                  Burglary          78748.0
10                                 Burglary          78758.0
11                               Auto Theft          78753.0
12                               Auto Theft          78744.0
13                              Agg Assault          78744.0
14                                 Burglary          78747.0
15                                 Burglary          78748.0
16                              Agg Assault          78704.0
17                              Agg Assault          78756.0
19                                 Burglary          78759.0
20                                 Burglary          78704.0
21                                 Burglary          78723.0
22                                 Burglary          78701.0
24                                 Burglary          78745.0
25                                 Burglary          78748.0
26                                 Burglary          78741.0
27                                 Burglary          78749.0
28                                    Theft          78701.0
29                                    Theft          78758.0
30                                    Theft          78744.0
31                                    Theft          78748.0
32                               Auto Theft          78744.0
...                                     ...              ...
37428                                 Theft          78723.0
37429                           Agg Assault          78752.0
37430                            Auto Theft          78752.0
37431                               Robbery          78725.0
37432                                 Theft          78617.0
37433                                 Theft          78754.0
37435                                 Theft          78705.0
37436                                 Theft          78735.0
37437                                 Theft          78704.0
37438                                 Theft          78745.0
37439                                 Theft          78756.0
37440                                 Theft          78702.0
37441                                 Theft          78741.0
37442                                 Theft          78722.0
37444                                 Theft          78758.0
37445                                 Theft          78754.0
37446                                 Theft          78758.0
37447                                 Theft          78744.0
37448                                 Theft          78735.0
37449                                 Theft          78756.0
37450                                 Theft          78735.0
37451                                 Theft          78749.0
37452                                 Theft          78741.0
37453                                 Theft          78745.0
37455                                 Theft          78752.0
37456                                 Theft          78757.0
37457                                 Theft          78701.0
37458                                 Theft          78723.0
37459                                 Theft          78742.0
37460                                 Theft          78705.0

[34885 rows x 2 columns]

In [11]:
crime.columns = ['CATEGORY','ZIP']

In [12]:
crime2 = pd.merge(crime, category, left_on='CATEGORY', right_on='CATEGORY', how='left', sort=False)

In [13]:
crime2 = crime2.dropna().drop(['Unnamed: 0','crime'],axis =1)

In [14]:
freq = crime2.groupby(by=['ZIP']).sum()[['score']]

In [15]:
freq=freq.reset_index()
freq.head()

       ZIP  score
0  78613.0  11175
1  78617.0  10235
2  78652.0    570
3  78653.0   1490
4  78660.0   5815

In [16]:
zip_pop =pd.read_csv('pop-by-zip-code.csv', sep=',', header=0, delimiter=',')
zip_pop = zip_pop[['zip_code','y-2016']]

In [17]:
zip_pop['zip_code']=zip_pop['zip_code']*1.0

In [18]:
d = zip_pop.set_index('zip_code')['y-2016'].to_dict()

In [19]:
freq['pop'] = freq['ZIP'].map(d)

In [20]:
freq 
freq['pop'].fillna(1, inplace=True)

In [21]:
freq['score/population'] = freq['score']/freq['pop']
freq.head()

       ZIP  score    pop  score/population
0  78613.0  11175  75279          0.148448
1  78617.0  10235  26126          0.391755
2  78652.0    570   4919          0.115877
3  78653.0   1490  19328          0.077090
4  78660.0   5815  81698          0.071177

In [22]:
freq['log'] = np.log(freq['score/population'])

In [34]:
import pickle
filePath = "./"
# listing = pd.read_csv(filePath)

bins = pickle.load( open( filePath +"bins.pickle", "rb" ) )
print(bins)
freq['level2'] = pd.qcut(freq['log'], 3,labels=[1,2,3],duplicates='drop')

[-11.10731535  -6.83780041  -2.88807444   3.87120101]

In [35]:
freq

        ZIP   score    pop  score/population       log level level2
0   78613.0   11175  75279          0.148448 -1.907522     3      1
1   78617.0   10235  26126          0.391755 -0.937118     3      1
2   78652.0     570   4919          0.115877 -2.155224     3      1
3   78653.0    1490  19328          0.077090 -2.562779     3      1
4   78660.0    5815  81698          0.071177 -2.642589     3      1
5   78701.0   74930   7401         10.124308  2.314939     3      3
6   78702.0   60425  22617          2.671663  0.982701     3      3
7   78703.0   24230  20815          1.164064  0.151918     3      2
8   78704.0   91330  46474          1.965185  0.675586     3      3
9   78705.0   41525  32414          1.281082  0.247705     3      2
10  78712.0     190    848          0.224057 -1.495857     3      1
11  78717.0   10495  27101          0.387255 -0.948672     3      1
12  78719.0    5745   1762          3.260499  1.181880     3      3
13  78721.0   20570  12153          1.692586  0.526258     3      3
14  78722.0    9795   7292          1.343253  0.295094     3      2
15  78723.0   77935  32496          2.398295  0.874758     3      3
16  78724.0   21785  24558          0.887084 -0.119816     3      2
17  78725.0    2720   7931          0.342958 -1.070147     3      1
18  78726.0    7960  13925          0.571634 -0.559257     3      2
19  78727.0   19155  29085          0.658587 -0.417659     3      2
20  78728.0     175  21858          0.008006 -4.827536     2      1
21  78729.0   20135  30151          0.667805 -0.403758     3      2
22  78730.0    1700   9038          0.188095 -1.670810     3      1
23  78731.0   18585  27401          0.678260 -0.388225     3      2
24  78732.0      35  16851          0.002077 -6.176817     2      1
25  78735.0   10545  16948          0.622197 -0.474498     3      2
26  78736.0    4265   7951          0.536411 -0.622856     3      1
27  78737.0      35  14731          0.002376 -6.042361     2      1
28  78739.0    5435  19564          0.277806 -1.280832     3      1
29  78741.0  125695  51981          2.418095  0.882980     3      3
30  78742.0    2150    714          3.011204  1.102340     3      3
31  78744.0   72350  47211          1.532482  0.426889     3      3
32  78745.0   83065  61317          1.354681  0.303566     3      2
33  78746.0   26890  27971          0.961353 -0.039414     3      2
34  78747.0    8730  19876          0.439223 -0.822748     3      1
35  78748.0   49020  47966          1.021974  0.021736     3      2
36  78749.0   27590  36478          0.756346 -0.279256     3      2
37  78750.0   11905  29991          0.396952 -0.923939     3      1
38  78751.0   33540  14648          2.289732  0.828435     3      3
39  78752.0   50360  19902          2.530399  0.928377     3      3
40  78753.0  116065  56131          2.067752  0.726462     3      3
41  78754.0   15270  21764          0.701617 -0.354367     3      2
42  78756.0   12160   8798          1.382132  0.323627     3      3
43  78757.0   40210  23611          1.703020  0.532403     3      3
44  78758.0   92990  46506          1.999527  0.692911     3      3
45  78759.0   42125  41415          1.017144  0.016998     3      2

In [36]:
freq.to_csv('safety_score_AU.csv', sep=',', encoding='utf-8')

In [37]:
freq['level2'].value_counts()

1    16
3    15
2    15
Name: level2, dtype: int64